// src/enums/action-type.enum.js
const ActionType = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    CHANGE_USER_STATUS: 'CHANGE_USER_STATUS',
    CREATE_SUBJECT: 'CREATE_SUBJECT',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',
    DELETE_SUBJECT: 'DELETE_SUBJECT',
    ASSOCIATE_USER_SUBJECT: 'ASSOCIATE_USER_SUBJECT',
    DISSOCIATE_USER_SUBJECT: 'DISSOCIATE_USER_SUBJECT',
    CREATE_CLASS_SCHEDULE: 'CREATE_CLASS_SCHEDULE',
    UPDATE_CLASS_SCHEDULE: 'UPDATE_CLASS_SCHEDULE',
    DELETE_CLASS_SCHEDULE: 'DELETE_CLASS_SCHEDULE',
    CREATE_AVAILABILITY_SCHEDULE: 'CREATE_AVAILABILITY_SCHEDULE',
    UPDATE_AVAILABILITY_SCHEDULE: 'UPDATE_AVAILABILITY_SCHEDULE',
    DELETE_AVAILABILITY_SCHEDULE: 'DELETE_AVAILABILITY_SCHEDULE',
    REQUEST_TUTORING: 'REQUEST_TUTORING', // <-- NUEVO
    APPROVE_TUTORING_REQUEST: 'APPROVE_TUTORING_REQUEST', // <-- NUEVO
    REJECT_TUTORING_REQUEST: 'REJECT_TUTORING_REQUEST', // <-- NUEVO
    CANCEL_TUTORING: 'CANCEL_TUTORING', // <-- NUEVO (incluye solicitudes y tutorías agendadas)
    MARK_ATTENDANCE: 'MARK_ATTENDANCE', // <-- NUEVO (para futuras funcionalidades)
    GENERATE_REPORT: 'GENERATE_REPORT', // <-- NUEVO
    EXPORT_REPORT: 'EXPORT_REPORT', // <-- NUEVO
    // Puedes añadir más tipos de acciones aquí
};

module.exports = ActionType;