// src/enums/report-type.enum.js
const ReportType = {
    TUTORINGS_COMPLETED: 'TUTORINGS_COMPLETED',
    STUDENT_ATTENDANCE: 'STUDENT_ATTENDANCE',
    TEACHER_PERFORMANCE: 'TEACHER_PERFORMANCE',
    GENERAL_STATISTICS: 'GENERAL_STATISTICS',
    SYSTEM_AUDIT: 'SYSTEM_AUDIT',
};

module.exports = ReportType;